<Project Sdk="Godot.NET.Sdk/4.5.0">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
      <Compile Include="TetrisTypes.fs" />
    <Compile Include="TetrisTickRelay.fs" />
    <Compile Include="TetrisBagPreview.fs" />
    <Compile Include="TetrisGridView.fs" />
    <Compile Include="TetrisUiBoard.fs" />
    <Compile Include="TetrisHud.fs" />
    <Compile Include="Tetris.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Headsetsniper.Godot.FSharp.Annotations" Version="0.9.4" />
  </ItemGroup>

</Project>
